from glob import glob


configfile: "config/config.yaml"


DATA_DIR = config["data_dir"]
HAZARD_DATA_DIR = config["hazard_data_dir"]
DATASET = config["dataset"]
hazard_slug = os.path.basename(config["hazard_csv"]).replace(".csv", "")
WORKFLOW_DIR = config['workflow_dir']

# Inputs #
import requests
r = requests.get("https://www.worldpop.org/rest/data/pop/cic2020_UNadj_100m")
COUNTRY_CODES = [row["iso3"] for row in r.json()["data"]]
#COUNTRY_CODES = ['PHL']

boxlen = 5  # width and height of boxes
all_boxes = [f"box_{int(idx)}" for idx in range(0, int((180--180)*(90--90)/boxlen**2))]
all_boxes = [f"box_{idx}" for idx in [1797, 1798, 1799, 1869, 1870, 1871, 1941, 1942, 1943, 2013, 2014, 2015, 2085, 2086, 2087, 1720, 1721, 1722, 1792, 1793, 1794, 1864, 1865, 1866, 1936, 1937]]


##### load rules #####


include: "rules/download/dryad-gdp.smk"
include: "rules/download/gadm.smk"
include: "rules/download/gridfinder.smk"
include: "rules/download/storm-ibtracs.smk"
include: "rules/download/worldpop-population.smk"
include: "rules/download/wri-powerplants.smk"
include: "rules/download_all.smk"
include: "rules/process/split-world.smk"
include: "rules/process/powerplants.smk"
include: "rules/process/targets.smk"
include: "rules/process/split-gridfinder.smk"
include: "rules/process/network.smk"
include: "rules/process/connector.smk"
include: "rules/process/assign-gdp.smk"
include: "rules/process_all.smk"
include: "rules/intersect/intsersect-storm.smk"
include: "rules/slice.smk"
include: "rules/filter_osm_data.smk"
include: "rules/convert_to_geoparquet.smk"
include: "rules/network_hazard_intersection.smk"
include: "rules/join_data.smk"


##### target rules #####


rule all:
    input:
        f"results/{DATASET}.highway-core_{hazard_slug}_splits.geoparquet",


rule clean:
    shell:
        """
        rm -rf data/slices &&
        rm -rf outputs/slices
        """
