from glob import glob


configfile: "config/config.yaml"


DATA_DIR = config["data_dir"]
HAZARD_DATA_DIR = config["hazard_data_dir"]
DATASET = config["dataset"]
hazard_slug = os.path.basename(config["hazard_csv"]).replace(".csv", "")
WORKFLOW_DIR = config['workflow_dir']

import requests

r = requests.get("https://www.worldpop.org/rest/data/pop/cic2020_UNadj_100m")
COUNTRY_CODES = [row["iso3"] for row in r.json()["data"]]


##### load rules #####


include: "rules/download/dryad-gdp.smk"
include: "rules/download/gadm.smk"
include: "rules/download/gridfinder.smk"
include: "rules/download/storm-ibtracs.smk"
include: "rules/download/worldpop-population.smk"
include: "rules/download/wri-powerplants.smk"
include: "rules/download_all.smk"
include: "rules/process/plants-targets.smk"
include: "rules/slice.smk"
include: "rules/filter_osm_data.smk"
include: "rules/convert_to_geoparquet.smk"
include: "rules/network_hazard_intersection.smk"
include: "rules/join_data.smk"


##### target rules #####


rule all:
    input:
        f"results/{DATASET}.highway-core_{hazard_slug}_splits.geoparquet",


rule clean:
    shell:
        """
        rm -rf data/slices &&
        rm -rf outputs/slices
        """
