[book]
title = "open-gira Documentation"
authors = ["Tom Russell", "Matt Jaquiery", "Fred Thomas"]
description = "User guide for the open-gira software."

[build]
build-dir = "build"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
# additional-css = ["custom.css"]

[output.html.search]
# limit-results = 15
